# Changes here will be overwritten by Copier
AddAllcontributors: true
AddCodeOfConduct: true
AddContributionDocs: true
AddCopierCI: false
AddGitHubTemplates: true
AddMacToCI: true
AddPrecommit: true
AddWinToCI: true
AnswerStrategy: ask
Authors: Abel Soares Siqueira <abel.s.siqueira@gmail.com> and Tangi Migot <tangi.migot@gmail.com>
AutoIncludeTests: true
CodeOfConductContact: tangi.migot@gmail.com
ConfigIndentation: 2
JuliaIndentation: 2
JuliaMinCIVersion: ^1.10.0
JuliaMinVersion: ^1.6.0
License: MPL-2.0
LicenseCopyrightHolders: Abel Soares Siqueira <abel.s.siqueira@gmail.com> and Tangi
    Migot <tangi.migot@gmail.com>
MarkdownIndentation: 2
PackageName: DCISolver
PackageOwner: JuliaSmoothOptimizers
PackageUUID: bee2e536-65f6-11e9-3844-e5bb4c9c55c9
RunJuliaNightlyOnCI: true
UseCirrusCI: false
_commit: v0.13.0
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
